### ISSUE TITLE
Error related to massdns binary

### ISSUE THREAD

**Issue by ghost** [fellchase/flumberboozle#2]
random@random-:~/flumberboozle/flumberbuckets$ python3 flumberbuckets.py -m '/home/random/massdns/bin/massdns' -w medium.txt -i dentrix
                        __ _                 _               _                _        _                             
                       / _| |_   _ _ __ ___ | |__   ___ _ __| |__  _   _  ___| | _____| |_ ___                       
                      | |_| | | | | '_ ` _ \| '_ \ / _ \ '__| '_ \| | | |/ __| |/ / _ \ __/ __|                      
                      |  _| | |_| | | | | | | |_) |  __/ |  | |_) | |_| | (__|   <  __/ |_\__ \                      
                      |_| |_|\__,_|_| |_| |_|_.__/ \___|_|  |_.__/ \__,_|\___|_|\_\___|\__|___/                      
                                                                                                                     
                      S3 Bucket Enumeration                                          @fellchase                      
                                                                                                                     
Traceback (most recent call last):                                                                  
  File "flumberbuckets.py", line 168, in <module>
    [q.put(x) for x in find_live_buckets()]
  File "flumberbuckets.py", line 149, in find_live_buckets
    output = subprocess.run("< {} {} | grep -v 's3-1-w.amazonaws.com' | grep -v directional | cut -d ' ' -f1 | sed 's/.s3.amazonaws.com.//'".format(potential_buckets_file, mdns_resolve), shell=True, capture_output=True)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'

Even tried supplying resolvers.txt file with this tag  --resolve resolvers.txt .

**Comment by fellchase** [comment]
Hi

This error is faced by people using Python 3.6 because the parameter capture_output is not present in Python 3.6 but only in 3.8

I'll be changing code to fix this please destroy the cloned "flumberboozle" directory and then again run git clone command to clone the repository in a new fresh folder, massdns directory doesn't need to be deleted

**Comment by fellchase** [comment]
Code pushed. Issue Fixed. Happy New Year

**Comment by ghost** [comment]
Thank You ! It works fine now . Same to you
